services:
  # Genetic Analysis Service - processes SNP data from WorldtreeTest contract
  genetic-analysis:
    # Using our custom worldtree genetic analysis image
    image: docker.io/cyama/worldtree-genetic-analysis:latest@sha256:b37a1c8d36ac7b9f7c5341e4761727d11a86751b93fd3fd2cc993f958a473aa7
    platform: linux/amd64
    environment:
      # WorldtreeTest contract address with correct ROFL app ID
      - CONTRACT_ADDRESS=0x614b1b0Dc3C94dc79f4df6e180baF8eD5C81BEc3
      # Keep ticker for demo oracle compatibility
      - TICKER=ROSEUSDT
    volumes:
      - /run/rofl-appd.sock:/run/rofl-appd.sock
