services:
  ollama:
    image: "docker.io/ollama/ollama"
    platform: linux/amd64
    ports:
      - "11434:11434"
    volumes:
      - /storage/ollama:/root/.ollama
    entrypoint: ["/usr/bin/bash", "-c", "/bin/ollama serve & sleep 5; ollama pull deepseek-r1:1.5b; wait"]
    healthcheck:
      test: ["CMD", "/bin/ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 5

  llm-api:
    image: docker.io/cyama/llm-api:latest@sha256:71bea9f279202cdaef4a6e47e6c13ac52b7b9d5814003cd258bbc28146fe06e5
    platform: linux/amd64
    ports:
      - "8080:8080"
    volumes:
      - /run/rofl-appd.sock:/run/rofl-appd.sock
    depends_on:
      ollama:
        condition: service_healthy
    restart: on-failure
    environment:
      - OLLAMA_URL=http://ollama:11434
      - LLM_BRIDGE_CONTRACT=0x32f22B267Be8CD47FAF93Bcd1CC31059bdc24FD2
