services:
  ollama:
    image: "docker.io/ollama/ollama"
    platform: linux/amd64
    ports:
      - "11434:11434"
    volumes:
      - /storage/ollama:/root/.ollama
    entrypoint: ["/usr/bin/bash", "-c", "/bin/ollama serve & sleep 5; ollama pull deepseek-r1:1.5b; wait"]
    healthcheck:
      test: ["CMD", "/bin/ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 5

  llm-api:
    build: ./services/llm-api
    platform: linux/amd64
    ports:
      - "8080:8080"
    volumes:
      - /run/rofl-appd.sock:/run/rofl-appd.sock
    depends_on:
      ollama:
        condition: service_healthy
    restart: on-failure
    environment:
      - OLLAMA_URL=http://ollama:11434
