services:
  # Genetic Analysis Service - processes SNP data from WorldtreeTest contract
  genetic-analysis:
    # Using our custom worldtree genetic analysis image
    image: docker.io/cyama/worldtree-genetic-analysis:latest@sha256:e161650a016e8e7b33e8e810e0add60a3a360cfb72608ecbfa87ff194701b7b0
    platform: linux/amd64
    environment:
      # WorldtreeTest contract address with correct ROFL app ID
      - CONTRACT_ADDRESS=0x614b1b0Dc3C94dc79f4df6e180baF8eD5C81BEc3
      # Keep ticker for demo oracle compatibility
      - TICKER=ROSEUSDT
    volumes:
      - /run/rofl-appd.sock:/run/rofl-appd.sock
