services:
  # Genetic Analysis Service - processes SNP data from WorldtreeTest contract
  genetic-analysis:
    # Using our custom worldtree genetic analysis image
    image: docker.io/cyama/worldtree-genetic-analysis:latest@sha256:83206873f8b63165a3d957c35b106eb02b6009b36ed78370245fa5fed37a8ac5
    platform: linux/amd64
    environment:
      # WorldtreeTest contract address with correct ROFL app ID
      - CONTRACT_ADDRESS=0x614b1b0Dc3C94dc79f4df6e180baF8eD5C81BEc3
      # Keep ticker for demo oracle compatibility
      - TICKER=ROSEUSDT
    volumes:
      - /run/rofl-appd.sock:/run/rofl-appd.sock
