services:
  # Genetic Analysis Service - processes SNP data from WorldtreeTest contract
  genetic-analysis:
    # Using our custom worldtree genetic analysis image
    image: docker.io/cyama/worldtree-genetic-analysis:backend-v2@sha256:3d2090772744acec2eed60405aed6ce274bc420a3850cb7ea65c907639271dc5
    platform: linux/amd64
    environment:
      # WorldtreeBackend contract address (privacy-preserving)
      - CONTRACT_ADDRESS=0xBc1437ae87B8111dC89e794eb6dD4B303901aCC1
      # Keep ticker for demo oracle compatibility
      - TICKER=ROSEUSDT
    volumes:
      - /run/rofl-appd.sock:/run/rofl-appd.sock
